
/**
 * This file is part of FastBangs. It is appended to the end of the javascript
 *  file generated by wasm-pack. It will be loaded by the browser extension as
 *  a background script.
 */

const runtime = browser.runtime;
const { process_query } = wasm_bindgen;

async function run() {
    await wasm_bindgen(runtime.getURL('fastbangs_wasm_bg.wasm'));
    browser.webRequest.onBeforeRequest.addListener((details) => {
        const url = new URL(details.url);
        const params = new URLSearchParams(url.search)
        const query = params.get('q');
        if (query === null) return { cancel: false }
        if (newloc = process_query(query)) {
            return { redirectUrl: newloc };
        }
    },
        { urls: ['*://*.google.com/search?*', '*://duckduckgo.com/?q=*'] }, ['blocking']);
}

run();